# Generated by Django 4.0.2 on 2022-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rejection_percentage', models.CharField(max_length=100)),
                ('reason_1', models.TextField()),
                ('reason_2', models.TextField()),
                ('reason_3', models.TextField()),
            ],
        ),
    ]
